language: go
go:
  - 1.4.2
  - tip
install:
  - go get google.golang.org/grpc
  - go get github.com/Shopify/go-lua
  - go get github.com/golang/protobuf/proto

script: go test -tags unit_test_executor ./executor
script: go test -tags unit_test_lua_engine ./executor/engine
