language: go

sudo: false

go:
  - 1.5

install:
  - go get github.com/tools/godep
  - godep restore

script: 
  - go test -tags unit_test_executor ./executor
  - go test -tags unit_test_lua_engine ./executor/engine
